/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 23-一月-2018 14:55:12 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

USE `autoshop`
;

SET FOREIGN_KEY_CHECKS=0

/* Drop Tables */

DROP TABLE IF EXISTS `customer_info` CASCADE
;

DROP TABLE IF EXISTS `garage_biz` CASCADE
;

DROP TABLE IF EXISTS `garage_biz_book` CASCADE
;

DROP TABLE IF EXISTS `garage_card_info` CASCADE
;

DROP TABLE IF EXISTS `garage_discount_coupon` CASCADE
;

DROP TABLE IF EXISTS `garage_info` CASCADE
;

DROP TABLE IF EXISTS `sys_dict` CASCADE
;

DROP TABLE IF EXISTS `sys_function` CASCADE
;

DROP TABLE IF EXISTS `sys_role` CASCADE
;

DROP TABLE IF EXISTS `sys_role_fun` CASCADE
;

DROP TABLE IF EXISTS `sys_user` CASCADE
;

DROP TABLE IF EXISTS `sys_user_role` CASCADE
;

DROP TABLE IF EXISTS `sys_wechat_info` CASCADE
;

DROP TABLE IF EXISTS `vehicle_info` CASCADE
;

DROP TABLE IF EXISTS `vehicle_maintain_detail` CASCADE
;

DROP TABLE IF EXISTS `vehicle_maintain_info` CASCADE
;

/* Create Tables */

CREATE TABLE `customer_info`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`name` VARCHAR(50),
	`gender` CHAR(1) COMMENT '0:female 1:mle 3:other',
	`phone_number` VARCHAR(20),
	`birthday` DATE,
	`user_id` INTEGER COMMENT 'id of table sys_user',
	CONSTRAINT `PK_customer_info` PRIMARY KEY (`id`)
)
;

CREATE TABLE `garage_biz`
(
	`id` MEDIUMINT NOT NULL AUTO_INCREMENT ,
	`category` INTEGER COMMENT '类别,1:维修 2:保养 3:洗车 4:其它',
	`code` VARCHAR(50) COMMENT '业务编码',
	`name` VARCHAR(50) COMMENT '业务名称',
	`price` FLOAT(0) COMMENT '价格',
	`garage_id` INTEGER COMMENT '所属车行',
	`desc` VARCHAR(200) COMMENT '业务详细描述',
	CONSTRAINT `PK_garage_biz` PRIMARY KEY (`id`)
) COMMENT='业务列表'
;

CREATE TABLE `garage_biz_book`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`type` VARCHAR(2) COMMENT '预约业务类别:1:',
	`state` INTEGER COMMENT '预约状态：0:预约 2:已接待 3:取消',
	`user_id` INTEGER COMMENT '预约用户',
	`book_time` TIMESTAMP COMMENT '预约时间',
	`garage_id` INTEGER COMMENT '预约车行',
	`plate_number` VARCHAR(50) COMMENT '车辆ID',
	`create_time` TIMESTAMP COMMENT '记录生成时间',
	`memo` TEXT COMMENT '备注说明',
	CONSTRAINT `PK_garage_biz_book` PRIMARY KEY (`id`)
)
;

CREATE TABLE `garage_card_info`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`type` CHAR(2),
	`value` FLOAT(0),
	`create_time` DATETIME COMMENT '开卡日期',
	`expired_date` VARCHAR(50) COMMENT '到期日',
	`user_id` INTEGER COMMENT '所属客户',
	`garage_id` INTEGER COMMENT '开卡车行',
	`create_user` INTEGER COMMENT '开卡员工',
	`desc` VARCHAR(50),
	CONSTRAINT `PK_garage_card_info` PRIMARY KEY (`id`)
)
;

CREATE TABLE `garage_discount_coupon`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`uniqu_code` VARCHAR(200) NOT NULL COMMENT '唯一编码，可识别此券',
	`type` CHAR(10) COMMENT '0:折扣 1:抵金券',
	`value` FLOAT(0) COMMENT '折扣、抵扣值',
	`is_active` CHAR(0) COMMENT '状态：0:未激活 1:已激活',
	`activte_date` DATE,
	`duration` VARCHAR(50),
	`expired_date` DATE COMMENT '到期日，若有活动期限，则与活动的结束日期一致；若按激活后按可使用时长算则active_date+ duration计算；若两者都有，则取两种计算结果较短者;若业务类型定义了不限定使用期限，则此列不生效',
	`valid_date_begin` DATE COMMENT '优惠券可使用的开始日期',
	`valid_date_end` DATE COMMENT '优惠券可使用的结束日期',
	`user_id` INTEGER COMMENT '关联的用户',
	`garage_id` INTEGER COMMENT '所属车行',
	`desc` VARCHAR(200) COMMENT '描述',
	CONSTRAINT `PK_garage_card_coupon` PRIMARY KEY (`id`)
)
;

CREATE TABLE `garage_info`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`name` VARCHAR(100) COMMENT '车行名称',
	`address` VARCHAR(200) COMMENT '车行地址',
	`lbs` TEXT COMMENT '定位地址',
	`desc` TEXT COMMENT '描述',
	CONSTRAINT `PK_garage_inf` PRIMARY KEY (`id`)
)
;

CREATE TABLE `sys_dict`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`cagegory_code` VARCHAR(50) COMMENT '数据字典类别代码',
	`code` VARCHAR(50) COMMENT '数据字典编码',
	`name` VARCHAR(50) COMMENT '名称',
	`desc` TEXT COMMENT '备注',
	CONSTRAINT `PK_sys_dict` PRIMARY KEY (`id`)
) COMMENT='数据字典'
;

CREATE TABLE `sys_function`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`name` VARCHAR(100),
	`req_uri` VARCHAR(250),
	`desc` TEXT,
	`parent_id` INTEGER,
	CONSTRAINT `PK_sys_function` PRIMARY KEY (`id`)
)
;

CREATE TABLE `sys_role`
(
	`role_code` VARCHAR(25) NOT NULL COMMENT '唯一角色代码',
	`name` VARCHAR(250),
	`role_desc` TEXT,
	CONSTRAINT `PK_sys_role` PRIMARY KEY (`role_code`)
)
;

CREATE TABLE `sys_role_fun`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`role_code` VARCHAR(25),
	`fun_id` INTEGER
)
;

CREATE TABLE `sys_user`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`login_name` VARCHAR(50),
	`password` VARCHAR(250),
	`state` INTEGER COMMENT '用户状态 0-正常 1-已删除',
	`garage_id` INTEGER COMMENT 'it tells that which garage does the user belong to ',
	`create_time` TIMESTAMP,
	`last_modify_time` TIMESTAMP,
	`last_modify_user` INTEGER,
	CONSTRAINT `PK_sys_user` PRIMARY KEY (`id`)
)
;

CREATE TABLE `sys_user_role`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`user_id` INTEGER,
	`role_code` VARCHAR(25),
	CONSTRAINT `PK_sys_user_role` PRIMARY KEY (`id`)
)
;

CREATE TABLE `sys_wechat_info`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`customer_id` INTEGER,
	`wechat_account` VARCHAR(100),
	`nick_name` VARCHAR(50),
	`head_portrait` BLOB,
	`open_id` VARCHAR(50),
	`unique_id` VARCHAR(50),
	CONSTRAINT `PK_sys_wechat_info` PRIMARY KEY (`id`)
)
;

CREATE TABLE `vehicle_info`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`plate_number` VARCHAR(50) COMMENT '车牌号',
	`vin` VARCHAR(50) COMMENT '车架号',
	`engine_number` VARCHAR(50) COMMENT '发动机号',
	`customer_id` INTEGER COMMENT '车主用户ID',
	`license_date` DATE COMMENT '上牌日期',
	`car_brand` VARCHAR(50) COMMENT '车辆品牌',
	`mileage` INTEGER COMMENT '当前里程',
	`insurance_date` DATE COMMENT '保险到期日',
	CONSTRAINT `PK_vehicle_info` PRIMARY KEY (`id`)
)
;

CREATE TABLE `vehicle_maintain_detail`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`maintain_id` INTEGER COMMENT '维护ID',
	`biz_code` VARCHAR(50) COMMENT '业务类型编码,取自车行业务表',
	`biz_name` VARCHAR(50) COMMENT '业务名称',
	`price` FLOAT(0) COMMENT '业务原价',
	`pay_price` FLOAT(0) COMMENT '客户应付款',
	`state` VARCHAR(2) COMMENT '服务状态,0:排队中 1:等待中 2:服务中 3:服务完成 ',
	`is_pay` CHAR(1) COMMENT '付款状态, 0:未付款 1:已付款',
	`start_time` TIMESTAMP COMMENT '业务开始时间',
	`end_time` TIMESTAMP COMMENT '业务完成时间',
	`desc` VARCHAR(200) COMMENT '明细说明',
	CONSTRAINT `PK_vehicle_maintain_detail` PRIMARY KEY (`id`)
)
;

CREATE TABLE `vehicle_maintain_info`
(
	`id` INTEGER NOT NULL AUTO_INCREMENT ,
	`state` VARCHAR(2) COMMENT '服务状态,0:排队中 1:服务中 2:服务完成 3:已交车',
	`category` VARCHAR(2) COMMENT '服务类别,1:维修 2:保养 3:洗车 4:其它',
	`vehicle_id` INTEGER COMMENT '车辆信息ID',
	`mileage` INTEGER COMMENT '此次维修保养里程',
	`battery_service_year` INTEGER COMMENT '截止当前电池使用年限',
	`tire_service_year` INTEGER COMMENT '轮胎已使用年限',
	`customer_id` INTEGER COMMENT '用户信息ID，交车保养维修用户，不一定是车主',
	`garage_id` INTEGER COMMENT '业务办理车行ID',
	`price` FLOAT(0) COMMENT '实际价格',
	`pay_price` FLOAT(0) COMMENT '客户应付款',
	`is_pay` CHAR(1) COMMENT '是否付款, 0:未付款 1:已付款',
	`memo` TEXT COMMENT '备注',
	`receive_time` TIMESTAMP COMMENT '车辆到店时间',
	`start_time` TIMESTAMP COMMENT '业务开始时间',
	`end_time` TIMESTAMP COMMENT '业务完成时间',
	CONSTRAINT `PK_vehicle_maintain_info` PRIMARY KEY (`id`)
)
;

INSERT INTO `sys_function` VALUES ('1', '用户管理',null,'system init',null);
INSERT INTO `sys_function` VALUES ('2', '新增用户','/sys/user/add','system init','1');
INSERT INTO `sys_function` VALUES ('3', '删除用户','/sys/user/del','system init','1');
INSERT INTO `sys_function` VALUES ('4', '更新用户','/sys/user/upt','system init','1');
INSERT INTO `sys_function` VALUES ('5', '更新用户','/sys/user/qry','system init','1');

INSERT INTO `sys_role` VALUES ('sys_admin','系统管理员','平台系统管理员');
INSERT INTO `sys_role` VALUES ('garage_admin','车行管理员','车行系统管理员');
INSERT INTO `sys_role` VALUES ('pub_customer','客户','车主');
INSERT INTO `sys_role` VALUES ('garage_receptionist','车行接待','车行接待员');

INSERT INTO `sys_role_fun` VALUES ('1','garage_admin','1');
INSERT INTO `sys_role_fun` VALUES ('2','garage_admin','2');
INSERT INTO `sys_role_fun` VALUES ('3','garage_admin','3');
INSERT INTO `sys_role_fun` VALUES ('4','garage_admin','4');
INSERT INTO `sys_role_fun` VALUES ('5','garage_admin','5');

INSERT INTO `GARAGE_INFO` VALUES ('1','酷鼎车行','广东省惠州市惠城区小金口',null,'系统测试');

INSERT INTO `sys_user` VALUES ('1','admin','E10ADC3949BA59ABBE56E057F20F883E' ,'0',null,now(),null,null);
INSERT INTO `sys_user` VALUES ('2','test1','E10ADC3949BA59ABBE56E057F20F883E' ,'0','1',now(),null,null);
INSERT INTO `sys_user` VALUES ('3','test2','E10ADC3949BA59ABBE56E057F20F883E' ,'0','1',now(),null,null);
INSERT INTO `sys_user` VALUES ('4','test3','E10ADC3949BA59ABBE56E057F20F883E' ,'0','1',now(),null,null);

INSERT INTO `sys_user_role` VALUES ('1','1','sys_admin');
INSERT INTO `sys_user_role` VALUES ('2','2','garage_admin');
INSERT INTO `sys_user_role` VALUES ('3','3','pub_customer');
INSERT INTO `sys_user_role` VALUES ('4','4','garage_receptionist');

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `customer_info` 
 ADD INDEX `IXFK_customer_info_sys_user` (`user_id` ASC)
;

ALTER TABLE `garage_biz` 
 ADD INDEX `IXFK_garage_biz_garage_info` (`garage_id` ASC)
;

ALTER TABLE `garage_biz_book` 
 ADD INDEX `IXFK_garage_biz_book_garage_info` (`garage_id` ASC)
;

ALTER TABLE `garage_biz_book` 
 ADD INDEX `IXFK_garage_biz_book_sys_user` (`user_id` ASC)
;

ALTER TABLE `garage_biz_book` 
 ADD INDEX `IXFK_garage_biz_book_vehicle_info` (`plate_number` ASC)
;

ALTER TABLE `garage_card_info` 
 ADD INDEX `IXFK_garage_card_info_garage_info` (`garage_id` ASC)
;

ALTER TABLE `garage_card_info` 
 ADD INDEX `IXFK_garage_card_info_sys_user` (`user_id` ASC)
;

ALTER TABLE `garage_discount_coupon` 
 ADD INDEX `IXFK_garage_card_coupon_garage_staff_info` (`garage_id` ASC)
;

ALTER TABLE `garage_discount_coupon` 
 ADD INDEX `IXFK_garage_card_coupon_sys_user` (`user_id` ASC)
;

ALTER TABLE `sys_role_fun` 
 ADD INDEX `IXFK_sys_role_fun_sys_function` (`fun_id` ASC)
;

ALTER TABLE `sys_user` 
 ADD INDEX `IXFK_sys_user_garage_info` (`garage_id` ASC)
;

ALTER TABLE `sys_user_role` 
 ADD INDEX `IXFK_sys_user_role_sys_role` (`role_code` ASC)
;

ALTER TABLE `sys_user_role` 
 ADD INDEX `IXFK_sys_user_role_sys_role_02` (`role_code` ASC)
;

ALTER TABLE `sys_user_role` 
 ADD INDEX `IXFK_sys_user_role_sys_user` (`user_id` ASC)
;

ALTER TABLE `sys_wechat_info` 
 ADD INDEX `IXFK_sys_wechat_info_customer_info` (`customer_id` ASC)
;

ALTER TABLE `vehicle_info` 
 ADD INDEX `IXFK_vehicle_info_customer_info` (`customer_id` ASC)
;

ALTER TABLE `vehicle_maintain_detail` 
 ADD INDEX `IXFK_vehicle_maintain_detail_vehicle_maintain_info` (`maintain_id` ASC)
;

ALTER TABLE `vehicle_maintain_info` 
 ADD INDEX `IXFK_vehicle_maintain_info_customer_info` (`customer_id` ASC)
;

ALTER TABLE `vehicle_maintain_info` 
 ADD INDEX `IXFK_vehicle_maintain_info_garage_info` (`garage_id` ASC)
;

ALTER TABLE `vehicle_maintain_info` 
 ADD INDEX `IXFK_vehicle_maintain_info_vehicle_info` (`vehicle_id` ASC)
;