/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 25-ʮ����-2017 17:28:40 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

USE `autoshop`
;

SET FOREIGN_KEY_CHECKS=0

/* Drop Tables */

DROP TABLE IF EXISTS `sys_function` CASCADE
;

DROP TABLE IF EXISTS `sys_role` CASCADE
;

DROP TABLE IF EXISTS `sys_role_fun` CASCADE
;

DROP TABLE IF EXISTS `sys_user` CASCADE
;

DROP TABLE IF EXISTS `sys_user_role` CASCADE
;

/* Create Tables */

CREATE TABLE `sys_function`
(
	`id` INTEGER NOT NULL,
	`name` VARCHAR(100),
	`req_uri` VARCHAR(250),
	`desc` TEXT,
	`parent_id` INTEGER,
	CONSTRAINT `PK_sys_function` PRIMARY KEY (`id`)
)
;

CREATE TABLE `sys_role`
(
	`id` INTEGER NOT NULL,
	`name` VARCHAR(250),
	`role_desc` TEXT,
	CONSTRAINT `PK_sys_role` PRIMARY KEY (`id`)
)
;

CREATE TABLE `sys_role_fun`
(
	`id` INTEGER NOT NULL,
	`role_id` INTEGER,
	`fun_id` INTEGER,
	CONSTRAINT `PK_sys_role_fun` PRIMARY KEY (`id`)
)
;

CREATE TABLE `sys_user`
(
	`id` INTEGER NOT NULL,
	`login_name` VARCHAR(50),
	`password` VARCHAR(250),
	`state` INTEGER,
	`create_time` TIMESTAMP,
	`last_modify_time` TIMESTAMP,
	`last_modify_user` INTEGER,
	CONSTRAINT `PK_sys_user` PRIMARY KEY (`id`)
)
;

CREATE TABLE `sys_user_role`
(
	`id` INTEGER NOT NULL,
	`user_id` INTEGER,
	`role_id` INTEGER,
	CONSTRAINT `PK_sys_user_role` PRIMARY KEY (`id`)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `sys_role_fun` 
 ADD INDEX `IXFK_sys_role_fun_sys_function` (`fun_id` ASC)
;

ALTER TABLE `sys_role_fun` 
 ADD INDEX `IXFK_sys_role_fun_sys_role` (`role_id` ASC)
;

ALTER TABLE `sys_user_role` 
 ADD INDEX `IXFK_sys_user_role_sys_role` (`role_id` ASC)
;

ALTER TABLE `sys_user_role` 
 ADD INDEX `IXFK_sys_user_role_sys_user` (`user_id` ASC)
;

ALTER TABLE `sys_user_role` 
 ADD INDEX `IXFK_sys_user_role_sys_user_02` (`user_id` ASC)
;